version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace/app
    volumes:
      - ./app:/workspace/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

volumes:
  postgres_data:
